[colors]
all_cpu_color = "#f5e0dc"
arc_color = "#89dceb"
avg_cpu_color = "#eba0ac"
border_color = "#585b70"
cpu_core_colors = ["#f38ba8", "#fab387", "#f9e2af", "#a6e3a1", "#74c7ec", "#cba6f7"]
cursor_color = "#f5c2e7"
gpu_core_colors = ["#74c7ec", "#cba6f7", "#f38ba8", "#fab387", "#f9e2af", "#a6e3a1"]
graph_color = "#a6adc8"
high_battery_color = "#a6e3a1"
highlighted_border_color = "#f5c2e7"
low_battery_color = "#f38ba8"
medium_battery_color = "#f9e2af"
ram_color = "#a6e3a1"
rx_color = "#a6e3a1"
selected_bg_color = "#cba6f7"
selected_text_color = "#11111b"
swap_color = "#fab387"
table_header_color = "#f5e0dc"
text_color = "#cdd6f4"
tx_color = "#f38ba8"
widget_title_color = "#f2cdcd"
