model = "gpt-5.2-codex"
model_reasoning_effort = "low"

[features]
web_search_request = true

[mcp_servers.notion]
type = "http"
url = "https://mcp.notion.com/mcp"

[mcp_servers.context7]
url = "https://mcp.context7.com/mcp"
http_headers = { "CONTEXT7_API_KEY" = "$(pass tokens/context7)" }

[projects."/Users/npv12/projects/simbian/SimbianOS"]
trust_level = "trusted"
