model = "gpt-5.3-codex"
model_reasoning_effort = "medium"
web_search = "cached"

[features]
multi_agent = true

[mcp_servers.context7]
http_headers = {"CONTEXT7_API_KEY" = "$(pass tokens/context7)"}
url = "https://mcp.context7.com/mcp"

[projects."/Users/npv12/dotfiles"]
trust_level = "trusted"

[projects."/Users/npv12/projects/simbian/SimbianOS"]
trust_level = "trusted"
